### ISSUE TITLE
More axis support

### ISSUE THREAD

**Issue by Evengard** [shauleiz/vJoy#15]
Hello!

While I was trying to emulate an XBOX 360 Controller with the help of VJoy, I stumbled upon a problem - not enough Axises. It seems that XBOX 360 controller uses Axises 9 and 10 for the separate Left and Right Trigger alongside of using the Axis 3 (Z axis) for both of them. Using only Axis 3 is not enough because when both triggers are simultaneously pressed the axis can't have two states at the same time.

Is it possible to implement into VJoy support for 2 more axises?

**Comment by WasabiFan** [comment]
I'm not involved in this project, but can speak from experience as a user. There's a separate xbox-specific branch and set releases for use with Xbox controllers. They emulate XInput devices, which is the same as normal Xbox controllers; using standard vJoy probably wouldn't get you what you want, because it emulates DirectInput devices instead (as most joystick drivers do). That branch works, but it's worth noting that it hasn't been updated in a while and can be a bit buggy. Also, the methods are terribly named, so good luck guessing which is which (hint: If it seems obvious, it isn't).

**Comment by shauleiz** [comment]
Please take a look at the common vJoy/vXbox API - [vGen](https://github.com/shauleiz/vGen).
