### ISSUE TITLE
ffb_strength

### ISSUE THREAD

**Issue by R1PeR** [shauleiz/vJoy#19]
Hi, I have been using vjoy for quite a while now and I made small program using it (https://github.com/R1PeR/MouseToVJoy), but I have a problem converting ffb calls to axis calls. I have seen that you created a program called ffbMon, which had variable ffb_strenght. Did you implemented this variable or do you have any idea how to do it? I found a way to implement Constant Force, but I have no idea how to do it for Periodic Force

**Comment by shauleiz** [comment]
Well, I have not touched on this code for several years so I'll just make a few guesses:

**ffb_strenght**: Never used in the code. 

I see no issue with "Periodic Force": There's a parameter ( Magnitude) that can be accessed by your code if you use my API:
Call function Ffb_h_Eff_Period(const FFB_DATA * Packet, FFB_EFF_PERIOD*  Effect).
Then use Effect.Magnitude as your value.

**Comment by evilC** [comment]
Hi, just FYI, I am writing a GUI app and have plans to support mouse -> vJoy (The old AHK version of our app supported it), although we use C# instead of C++  
Mouse "Delta" input and FFB are currently on my to-do list, if you are at all interested you are welcome to join us and help out!  
https://github.com/snoothy/UCR

**Comment by R1PeR** [comment]
I had to retrieve periodic offset to make it work, thanks anyway :)

**Comment by R1PeR** [comment]
@evilC hit me up with pm at sebastian.walus@op.pl, I will be more than happy to help you :)
