### ISSUE TITLE
Windows 10 (1909) invalid

### ISSUE THREAD

**Issue by luckart** [shauleiz/vJoy#34]
Installation succeeded but did not work

**Comment by jshafer817** [comment]
Just tested 1909.. and... it worked for me.  But.. I don't have secure boot enabled on this pc, and I boot MBR.. Anyone else want to verify??

**Comment by OR-WS** [comment]
Have a report in my group of someone who also hasn't managed to get it installed under W10 x64 v1909. Fresh install after a format.

I myself cannot verify because I am not going to risk breaking vJoy by updating from v1903 to v1909. That would prevent me from playing pretty much the only game I play.

Also, who should we now consider to be the lead developer for vJoy, you or jshafer817? I recall jshafer817 fixing similar issues after a Windows upgrade in the past when driver signing broke it.

**Comment by OR-WS** [comment]
> Just tested 1909.. and... it worked for me. But.. I don't have secure boot enabled on this pc, and I boot MBR.. Anyone else want to verify??

On the money, sir. Just had that person within our group test with secure boot ON and OFF. ON causes the installer to hang. OFF works fine. Hope this of use to you. User is using a GPT partition, not an MBR.

**Comment by jshafer817** [comment]
Tested in Vmware Workstation.. secure boot enabled with uefi booting.. Worked for me...

Fresh install... ???

**Comment by OR-WS** [comment]
I'm not sure what you're asking/suggesting? In any case, based on your comment we tried with secure boot ON/OFF. As indicated in my previous post, we're talking a fresh install on a GPT boot partition with secure boot OFF. That's when the installer seems to work. Switch secure boot ON and it hangs.

**Comment by OR-WS** [comment]
Unfortunately I was forced to install v1909 today as well. Same behavior as others have found, with Secure Boot enabled the installer hangs at 100% with only a task kill as your remaining option.

When may the users expect a fix?

**Comment by OR-WS** [comment]
Any news on this at all?

**Comment by shauleiz** [comment]
Please note that I do not develop vJoy any more.
Perhaps you could ask jshafer817 for help.
